swipe:
  3: 
    left:
      command: 'xdotool key alt+Left'
    rigth:
      command: 'xdotool key alt+Right'
    up: 
      command: 'xdotool key super'
    down: 
      command: 'xdotool key super'
  4:
    up: 
      command: 'xdotool key ctrl+alt+Down'
    down: 
      command: 'xdotool key ctrl+alt+Up'


threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1
